version: '3'
services:
  db:
    image: mysql/mysql-server:8.0
    hostname: db
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=microblog
      - MYSQL_USER=microblog
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    hostname: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  microblog:
    build: .
    hostname: microblog
    env_file: .env
    environment:
      - DATABASE_URL=mysql+pymysql://microblog:${MYSQL_PASSWORD}@db/microblog
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - MAIL_SERVER=smtp.googlemail.com
      - MAIL_PORT=587
      - MAIL_USE_TLS=true
    depends_on:
      - db
      - elasticsearch
    ports:
      - "8000:5000"

volumes:
  db-data:
  elasticsearch-data:
